using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.EntityFrameworkCore;

namespace TeachingLoadInfoSystem
{
    public partial class LastYearTeachinLoadGridForm : DevExpress.XtraEditors.XtraForm
    {
        public LastYearTeachinLoadGridForm()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            TeachingLoadInfoSystem.AppDbContext.TLDbContext dbContext = new TeachingLoadInfoSystem.AppDbContext.TLDbContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.EducationPlanPerGroups.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                educationPlanPerGroupsBindingSource.DataSource = dbContext.EducationPlanPerGroups.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}
