using TeachingLoadInfoSystem.AppDbContext;
using TeachingLoadInfoSystem.Models;
using TeachingLoadInfoSystem.Repositories;
using TeachingLoadInfoSystem.Services;
using TeachingLoadInfoSystem.Services.Intefaces;
using Microsoft.EntityFrameworkCore;

namespace TeachingLoadInfoSystem
{
    public partial class TLExcludedInnerGridForm : DevExpress.XtraEditors.XtraForm
    {
        TLDbContext db = new TLDbContext();
        TLExcluded excluded = new TLExcluded();
        TeachingLoad teachingLoad = new TeachingLoad(); 
        ITeachingLoadServices _teachingLoadServices;
        ITeachingLoadSubjectServices _teachingLoadSubjectServices;
        string argument;
        public void RefreshGrid()
        {
            var teachingLoads = _teachingLoadServices.GetAllTeachingLoads().ToList();
            var teachingLoadSubject = _teachingLoadSubjectServices.GetAllTeachingLoadSubjects().ToList();
            gridControl.DataSource = teachingLoadSubject;
            //colSubjects.FieldName = teachingLoad.TeachingLoadSubjects.Count.ToString();
            //foreach (var item in teachingLoads)
            //{
            //    gridControl.DataSource = item.TeachingLoadSubjects;
            //}
            //for (int i = 1; i < teachingLoads.Count; i++)
            //{
            //    gridControl.DataSource = teachingLoads[i];
            //}
        }
        public void PreviewData()
        {
        }
        public void RemoveData()
        {
            var index = gridView.FocusedRowHandle;
            if (index > -1)
            {
                var message = MessageBox.Show("Məlumatı silməyə əminsiniz?", "Sual", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                if (message == DialogResult.Yes)
                {
                    var selectedRow = Convert.ToInt32(gridView.GetFocusedRowCellValue("ID"));
                    var selectedCode = gridView.GetFocusedRowCellValue("TLExcludedCode");

                    _teachingLoadServices.DeleteTeachingLoad(selectedRow);
                    Refresh();

                    MessageBox.Show(selectedCode + " kodlu məlumat uğurla silindi.");
                }
                else
                {
                    MessageBox.Show("Hər hansı bir sətri seçin.");
                }
                RefreshGrid();
            }
        }
        public TLExcludedInnerGridForm()
        {
            InitializeComponent();
            TLDbContext db = new TLDbContext();
            _teachingLoadServices = new TeachingLoadServices(new Repository<TeachingLoad>(db));
            _teachingLoadSubjectServices = new TeachingLoadSubjectServices(new Repository<TeachingLoadSubject>(db));
            RefreshGrid();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            TeachingLoadInfoSystem.AppDbContext.TLDbContext dbContext = new TeachingLoadInfoSystem.AppDbContext.TLDbContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TeachingLoadSubjects.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                teachingLoadSubjectsBindingSource.DataSource = dbContext.TeachingLoadSubjects.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        private void newBtn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
        }

        private void RefreshBtn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            RefreshGrid();
        }

        private void previewBtn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            PreviewData();
        }

        private void gridControl_DoubleClick(object sender, EventArgs e)
        {
            PreviewData();
        }

        private void DeleteBtn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            RemoveData();
        }
    }
}